<Search>:
    #Set background color
    canvas:
        Color:
            rgb: [.5, .5, .95]
        Rectangle:
            pos: self.pos
            size: self.size
    AnchorLayout:
        TextInput:
            size: 300, 30
            size_hint: None, None
            multiline: False
    AnchorLayout:
        anchor_y: 'bottom'
        size_hint: 0, 0.25
        Button:
            text: 'Confirm'
            size_hint: None, None
            size: 100, 50